### PR TITLE
Sort options selectors to improve usability and accessibility

### PR DESCRIPTION
**Pull request by Ucodia**
Improve the usability and accessibility of the selector components by:
- Sorting options for easier scrolling
- Increase the contrast of non selected options for better visibility

## Issue number

None.

## Description

The `Select` component is currently showing non selected items in the same contrast as disabled items, which impacts its accessibility.

Screen Shot 2021-01-26 at 11 52 45 PM

The `AddRecord` component is creating selectors from list of items that seems to be in a random order which makes scrolling harder since there is no way to tell where an item might be in a very long list.

Screen Shot 2021-01-26 at 11 30 21 PM

## List of features added/changed

- Selector: Increased visibility of non selected options
- AddRecord: Sorted coin selector options
- AddRecord: Sorted text record type selector options

## How Has This Been Tested?

Change was tested by running the app locally with `yarn start`, the app was working as expected.
Unfortunately I was not able to run the Jest tests or the Cypress tests, both failed with errors unrelated to change.

```
 FAIL  src/components/SingleName/NameRegister/registerReducer.test.js
  ● getStates returns the correct states in order

    TypeError: (0 , _registerReducer.getStates) is not a function
```

Note that the change is local to this component only and should not impact other areas of the app.

## Screenshots (if appropriate):

Before
Screen Shot 2021-01-26 at 11 30 21 PM

After
Screen Shot 2021-01-26 at 11 51 30 PM

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by makoto** [comment]
Hi, @Ucodia thanks for the very detailed PR request.
Sorting by alphabet makes sense.

The jest test failure seems happening on dev branch so at least this PR didn't introduce.

However, your change caused our CI test failure as record edit page no longer show top 5 popular records

Screenshot 2021-01-28 at 10 06 34

Screenshot 2021-01-28 at 10 09 35


The left is your PR and the right is `dev`.

We prefer to show all the popular coins. Would you be able to modify your PR to keep this part as is?

**Comment by Ucodia** [comment]
Oh I see, this is an unexpected side effect I did not notice. I will have another look and fix. Thanks for sharing the screenshots, that's very useful 👍

**Comment by Ucodia** [comment]
I fixed the issue and sent a fix.

**Comment by makoto** [comment]
This time the test passed. Thank you for your contribution!

**Pull request merged**
