### PR TITLE
[WIP] ENS Keybase Integration

### PR DESCRIPTION
**Pull request by mul1sh**
## Issue number

#1053 

## Description

This is a WIP PR that will eventually enable ens domains integration with keybse

## List of features added/changed

[x] Keybase `config.json`

## How Has This Been Tested?

Yep

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by makoto** [comment]
Hi, thank you for the PR. You mentioned that this is WIP but you still want me to merge?
What does this PR enable at this stage and how do I test?

**Comment by mul1sh** [comment]
@makoto no this is not ready at all for merging, thats why I made it a draft PR so that it can't be merged. 

So eventually this will fix #1053 as stated above, and so i'm going to make more commits that will eventually make this happen, in the next few days.  Because i'm currently testing out a few approaches to the keybase-ens integration.

**Comment by makoto** [comment]
Ah ok. Can you close this for now and reopen when ready? No need to have WIP PR unless you are expecting for some comment.

**Comment by mul1sh** [comment]
Ok cool.

**Pull request closed without merging**
