### PR TITLE
Add support for ART domains

### PR DESCRIPTION
**Pull request by alexandergu**
Added .art to the list of supported TLDs
Displayed a list of the art records

### CODE REVIEW

**Comment by makoto** [comment]
hello, @alexandergu can you resolve conflicts? We made some big changes as part of ENS registry migration

**Comment by alexandergu** [comment]
Hello, @makoto! I resolved conflicts. 
In case of any questions feel free to write
Thank you!

**Comment by makoto** [comment]
Hi, just checked the merged version and it lists art records fine.
What would happen for adding/removing records?  Can you transfer some test domain on the prod or test net to 0xfFD1Ac3e8818AdCbe5C597ea076E8D3210B45df5 so that I can poke around?

**Comment by makoto** [comment]
Also has .art domain controller contract migrated to new one points to new ENS registry?

We haven't tested our UI against your domain so not sure if it's a but on our side, but it says it's not migrated.

Screenshot 2020-02-18 at 18 27 15

**Comment by makoto** [comment]
Hi, this is how the page looks.

Screenshot 2020-02-18 at 19 07 29

I will be merging this as it is less likely to impact other namespace, but please grant me a test username so that I can do a further tests.

Please also bear in mind that once we integrate with graphql, we should be able to display any key/value pair without hard coding each field hence we may refactor it to make it more generic in the future.

**Pull request merged**
