### PR TITLE
Fix external link for onion addresses

### PR DESCRIPTION
**Pull request by ricott1**
I fixed the external link for onion addresses, adding also the onion3 protocol type

### CODE REVIEW

**Comment by jefflau** [comment]
Thanks!

**Comment by jefflau** [comment]
FYI the `.link` was so people can direct to it in their normal browsers. If you know a better gateway that is more reliable let me know. We've done the same for IPFS and swarm

**Comment by ricott1** [comment]
I see, so I can just append `.link` and have the browser resolve the onion address with some gateway? I think, I don't understand, or at least it doesn't seem to work with, say, duckduckgo onion address: https://3g2upl4pq6kufc4m.onion

**Comment by jefflau** [comment]
Yeah that's supposedly how it's supposed to work. Is the only way you

**Comment by ricott1** [comment]
Since is not really working, do you think is worth leaving it anyway? Without the `.link` at least it would work for someone using the tor browser (which is the only useful case-scenario anyway)

**Comment by jefflau** [comment]
That's fair. I think maybe we should just leave it out then. I wasn't sure if it was just the links I was using wasn't working or it was everything

**Comment by ricott1** [comment]
Hi Jeff, could you also take a look at this other [PR](https://github.com/ensdomains/ui/pull/19)? I think right now the ens-app page doesn't work properly when you try to set some contenthash, not necessarily an onion address

**Comment by jefflau** [comment]
@ricott1 What happens with non-onion related contenthashes?

**Comment by ricott1** [comment]
if i try to set an ipfs:// contenthash it crashes, because we don't check for the length of the content (see the file changes). It was fine with the old version of content-hash, but now it throws the error. Similarly, if we set an invalid ipfs address it throws and crashes.

**Comment by jefflau** [comment]
Sorry I was super busy in India. I'll look into this again tomorrow. Apologies for the delay

**Comment by jefflau** [comment]
I have merged this through a local commit (so I could add the UI package) and deployed. Can you please check if it is running correctly?

**Comment by ricott1** [comment]
Looks like it's all working fine, thanks! 

Just a last small detail, I see you merged also the other [PR](https://github.com/ensdomains/ui/pull/19/files), but in the `onion3://` suggestion added in  `src/utils/records.js` is still not showing, and at the moment one cannot save a onion3 address with `onion://` (I hope it's clear what I mean).

**Comment by jefflau** [comment]
> PR

Not 100% sure of what you mean. Do you want to put in another PR to fix it? I should have updated to the latest `@ensdomains/ui`

**Comment by ricott1** [comment]
Yeah, it's weird because I see the [file](https://github.com/ensdomains/ui/blob/master/src/utils/records.js) is correct after the merge, but in the [ens-app](https://manager.ens.domains/) if I try to manage an address I have and edit the content, the `onion3://` suggestion does not show up.

**Comment by jefflau** [comment]
Can you try hardrefreshing? CMD + SHIFT + R on mac, our hosting caches sometimes

**Comment by ricott1** [comment]
Yeah, I thought it could be that but it still does not show it.
 Does it work for you? If that is the case then no worries

**Comment by jefflau** [comment]
Sorry for the slow reply - you are talking only about the placeholder? I was a bit confused before I think

**Comment by ricott1** [comment]
I was talking about the placeholder text. Since to set an onion3 address one has to explicitly specify `onion3://` I thought it was confusing if the option wasn't there in the placeholder.

**Comment by LeonmanRolls** [comment]
Out of date, closing for now, reopen if necessary.

**Pull request closed without merging**
