### PR TITLE
Error page invalid characters

### PR DESCRIPTION
**Pull request by arnaud-eb**
## Issue number
#1370

## Description
If an account has one or more domain names containing UTS46 forbidden characters (e.g. "???.eth"), the ens app goes blank. See example from issue:
https://app.ens.domains/address/0xC66135b1671aD1f2cAE217ff19234A77F7A0B00c

This PR catches the error and renders an error page inviting the user to go back to the home page.   

## List of features added/changed

- Update initial value `globalErrorReactive` variable
- Update `globalError` field on `Query` type in cache policy
- Abstract `GET_ERRORS` query to the queries file
- Update argument `globalErrorReactive` variable
- Subscribe to the value of `globalErrorReactive` in `Address` and `Favourites` components 
- Catch error invalid characters in `filterNormalised` method and update `globalErrorReactive` variable
- Reset `globalErrorReactive` variable when user goes back to home page
- Add `InvalidCharacterError` component
## How Has This Been Tested?

Run changes against existing unit tests and I will add a unit test to `utils.spec.js` in a further push:
image

## Screenshots (if appropriate):
image

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by royalfork** [comment]
This error page is certainly better than crashing (thanks!), but would it be possible to only show an error for the "problem" domain?  And if the address owns other "UTS-46 legal" domains, show those as normal?  I understand this is probably a pretty small edge case, but if it's easy to implement, that might be better than a complete bail-out to the homepage.

**Comment by LeonmanRolls** [comment]
Hey @arnaud-eb great work so far. I tried this out locally and it seems once the error state is set even if you navigate to a page with valid addresses it will still give the error message, so it should be cleared once the user navigates. Easiest way to reproduce this is to click on 'My Account' after visiting the example address you posted above, assuming your account doesn't have invalid names.

**Comment by LeonmanRolls** [comment]
@royalfork thanks for your suggestion. I will merge this once it is ready as it is an improvement on what we currently have, and create a separate issue to not throw the whole page.

**Comment by arnaud-eb** [comment]
Hi @LeonmanRolls, thanks. The error state is now reset when navigating to another address.

**Comment by arnaud-eb** [comment]
Fixes #1346

**Pull request merged**
