### PR TITLE
Use the @ethvault/iframe-provider-polyfill to support iframe wallets

### PR DESCRIPTION
**Pull request by moodysalem**
See https://github.com/ensdomains/ens-app/pull/388 for context

### CODE REVIEW

**Comment by moodysalem** [comment]
It looks like the package @ensdomains/ui contains the web3 setup code. It doesn't look like a user choice AFAICT. I can add the following to that package in setupWeb3, if preferable:

- check if window is in iframe
- - if in iframe, try creating an iframe provider with a target origin of 'https://ethvault.xyz'
- - try to enable the iframe provider via `await iframeProvider.enable()`
- - - if enable succeeds, set `window.ethereum` and `window.web3` to `iframeProvider`
- - - if enable fails or takes longer than 1 second, do nothing
- if not in iframe, do nothing

Since it's shared code, it would enable the provider in all the ENS apps that use it.

**Comment by moodysalem** [comment]
I will pursue an audit via https://github.com/EthereumCommonwealth/Auditing/issues/351

**Comment by moodysalem** [comment]
Here is that alternative implementation
https://github.com/ensdomains/ui/pull/18

**Comment by makoto** [comment]
Duplicate to https://github.com/ensdomains/ens-app/pull/421

**Pull request closed without merging**
