### PR TITLE
Upgraded ui package which include ethvault support

### PR DESCRIPTION
**Pull request by makoto**
@moodysalem this change includes https://github.com/ensdomains/ui/pull/18 and deployed into 
 https://imaginary-summer.surge.sh . Can you somehow check if it's working correctly ?

### CODE REVIEW

**Comment by moodysalem** [comment]
Yes, you can see it here.

https://myethvault.com/browse#imaginary-summer.surge.sh

It’s expected that if you log in via Ethvault and unlock an account you can see it in ENS but the change doesn’t seem to have worked. Will have to investigate this evening

**Comment by moodysalem** [comment]
This is the exception
```
Failed to create and enable iframe provider TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
```
I didn't pass an array to `Promise.race` :man_facepalming:

**Comment by moodysalem** [comment]
This should fix
https://github.com/ensdomains/ui/pull/20/files

**Comment by makoto** [comment]
Duplicate with https://github.com/ensdomains/ens-app/pull/421

**Pull request closed without merging**
