### PR TITLE
Fix travis builds on pull requests (#535)

### LINKED ISSUE #535: Travis build fails on Pull Requests from external repos
This is a followup from discussion in https://github.com/ensdomains/ens-app/pull/512. 

Relevant error from travis:
```
> ens-app@1.1.9 cypress:record /home/travis/build/ensdomains/ens-app
> yarn run cypress run --record --key $CYPRESS_TOKEN
$ /home/travis/build/ensdomains/ens-app/node_modules/.bin/cypress run --record --key
  error: option `-k, --key <record-key>' argument missing
error Command failed with exit code 1.
```

The same issue is with the other pull requests currently failing to build. The variable $CYPRESS_TOKEN is not set within travis environment, so the cypress run fails.

I understand that this is intended behaviour to prevent leaking of sensitive data through travis. The secret environment variables are not available in pull requests from other repositories. See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions for more info:

> If your build relies on encrypted variables to run, for instance to run Selenium tests with BrowserStack or Sauce Labs, your build needs to take this into account. You won’t be able to run these tests for pull requests from external contributors.
> 
> To work around this, restrict these tests only to situations where the environment variables are available, or disable them for pull requests entirely,

I'm not sure on the best approach to fix this. Change travis configuration (and probably package.json scripts) in a way that --record option is only used on the master branch? I think it depends on the requirements you have - when do you require to record the test run and when not?

_Originally posted by @TripleSpeeder in https://github.com/ensdomains/ens-app/pull/512#issuecomment-555903250_

### PR DESCRIPTION
**Pull request by TripleSpeeder**
Trying to fix #535 in a way that cypress runs work again in travis and are recorded when possible (read: when PR is from ens-app repo) 

Changes:
- Add shell script "cypress-run.sh" that checks for presence of $CYPRESS_TOKEN before trying to record cypress
- Drop cypress:ci script in favor of cypress:run as it was just calling cypress:run anyway.

### CODE REVIEW

**Comment by jefflau** [comment]
I saw travis builds working on the other PR. What does this do that is different?

**Comment by TripleSpeeder** [comment]
> I saw travis builds working on the other PR. What does this do that is different?

Technically it's doing the same (check for presence of $CYPRESS_TOKEN), but also cleans up some redundancies in the package.json scripts and moves some logic to the bash script "cypress-run.sh". So that overall package.json is less cluttered.

It's not mandatory, just trying to clean up a bit. I'll rebase later then you can have a look if you like it or not :)

**Comment by jefflau** [comment]
Looks great to me

**Comment by LeonmanRolls** [comment]
As this is quite old i'm going to assume it's no longer relevant. Let me know if it still needs merging, thanks @TripleSpeeder for the contribution!

**Pull request closed without merging**
