### PR TITLE
Test registrar

### PR DESCRIPTION
**Pull request by makoto**
If you are connected to Rinkeby or Ropsten and search an `.test` name which is not owned by anyone, you should be able to claim the ownership by pressing "Claim the test domain".

screen shot 2019-02-14 at 09 53 39

The change is deployed at https://imaginary-summer.surge.sh

### CODE REVIEW

**Comment by Arachnid** [comment]
Can you make the button just 'Claim' or 'Claim for 28 days'?

**Comment by jefflau** [comment]
I've asked for a design review from Becca for this

**Comment by rliebert90** [comment]
@makoto just some small notes! Can the 'claim domain' bttn be left aligned with where the rule above it ends? It should visually line up with the details/subdomain toggle above. Last thing - can the text below change to overpass semibold size 14pt, with this lighter color: C7D3E3. At the smaller size, the text can sit next to the bttn instead of below. Will look like this: 
screen shot 2019-02-18 at 1 30 09 pm

**Comment by makoto** [comment]
> Can you make the button just 'Claim' or 'Claim for 28 days'?

That gives the impression that the domain owner is automatically reset to empty after 28 days (that's what I initially thought the feature is).

**Comment by makoto** [comment]
> @makoto just some small notes! Can the 'claim domain' bttn be left aligned with where the rule above it ends? It should visually line up with the details/subdomain toggle above. Last thing - can the text below change to overpass semibold size 14pt, with this lighter color: C7D3E3. At the smaller size, the text can sit next to the bttn instead of below. Will look like this:
> screen shot 2019-02-18 at 1 30 09 pm

Doesn't that make mobile look too narrow?

screenshot 2019-02-19 at 17 12 15

**Comment by Arachnid** [comment]
> That gives the impression that the domain ownership is automatically reset to empty after 28 days (that's what I initially thought this feature is). In reality , majority of test domains stay because most people don't reset someone else's name.

I'm okay with  people having that impression.

**Pull request merged**
