### PR TITLE
Add option to register onion address

### PR DESCRIPTION
**Pull request by ricott1**
This pull is similar to #328 . I don't know how to update a pull from someone else, so I created a new one.

I added the option to register an onion address, encoded as a [multiaddress](https://github.com/multiformats/js-multiaddr), in the `contenthash` entry.

This pull will work in tandem with a [metamask pull](https://github.com/MetaMask/metamask-extension/pull/6629).

It depends on another pull made on the [content-hash](https://github.com/pldespaigne/content-hash/pull/24) dependency.

### CODE REVIEW

**Comment by Arachnid** [comment]
@jefflau PTAL

**Comment by jefflau** [comment]
Hi @ricott1, 

Sorry for the delay at looking at this.

We've moved this functionality in the most recent refactor to https://github.com/ensdomains/ui

Is it possible you could make this pull request on that repo?

**Comment by ricott1** [comment]
Hi @jefflau ,
Do you mean to include the possibility to encode onion in the src/utils/contents.js file?

**Comment by ricott1** [comment]
Closing, PR now at https://github.com/ensdomains/ui/pull/13

**Pull request closed without merging**
