### PR TITLE
feat: add gitpod support

### PR DESCRIPTION
**Pull request by bigint**
## Description

Gitpod helps contributors to fire a new workspace all setup

- Contribute from iPad
- Don't need local setup
- Saves local system space
- Easy to share demo with others

image

## How Has This Been Tested?

- Signup to Gitpod
- Open https://gitpod.io/#https://github.com/bigint/ens-app/tree/bigint/gp-support

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by bigint** [comment]
The problem is we need to update of node version to 16 in `package.json`

```json
"engines": {
    "node": "v16"
},
```

**Comment by makoto** [comment]
Hi. 
Thank you for your contribution. Did you run it locally with v16 and worked fine? I remember I once tried to upgrade to v15 and had to downgrade to v14 for some dependency issues.

**Comment by bigint** [comment]
Yup tested in v16 it works perfectly @makoto 👍🏻

**Comment by makoto** [comment]
Hi @bigint 

Can you try to run `yarn test:coverage` on your local v16 env?
I am working on PR to upgrade v16 but the unit test is showing the following error


```

 RUNS  src/setup.spec.js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read property 'getRandomValues' of undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

https://app.travis-ci.com/github/ensdomains/ens-app/jobs/548836621

**Comment by makoto** [comment]
@bigint hi. any response on my q above?

**Comment by bigint** [comment]
@makoto Sorry for the late reply was bit busy with other works, I see more cases fails :(

Screenshot 2021-11-23 at 10 06 30 PM

**Comment by makoto** [comment]
Umm, I don't think I got the error. Either way, can't upgrade to v16 until it all passes the test

**Comment by makoto** [comment]
Am I correct to understand that the gitpod cannot be used until it gets upgraded to v16?

**Comment by bigint** [comment]
@makoto Yes I think, anyhow i'll look for a chance to use 14 😄

**Pull request merged**
