### PR TITLE
Remove sanitisation from /name/[name]

### PR DESCRIPTION
**Pull request by jefflau**
In accordance with widespread support for DNS names on ENS, the ENS manager needs to start supporting other names without a whitelist of domains.  The reason the sanitisation is in, is so we can show error messages for short names and also show additional information for auction and domains that can be registered via the sub domain registrar. As the permanent registrar comes closer to launch, it is less likely these will be implemented (especially the auction) and therefore the manager must slowly remove sanitisation and add tools for users to search any kind of domain. Currently we have a sanitisation on both search and on direct URL search. This PR removes the sanitisation for just the name page, but leaves the search sanitisation in. The main goal of this PR is to allow any name to be namehashed if the direct url is given.

closes #99

### CODE REVIEW

**Comment by makoto** [comment]
screenshot 2019-02-19 at 15 58 59

The left (this PR) is allowing `resolver`. Shouldn't you at least check if `.` exists?

If possible, can you write unit tests validating the followings?

- `a.b` => valid (it's just that no one can register 1 char name)
- `.` => not valid
- `.a` => not valid
- `a.` => not valid
- `a` => not valid

**Comment by Arachnid** [comment]
@makoto These are all good validation rules (the last is handled by explicitly running `nameprep`). I'd prefer to drop the existing overzealous validation now, though, so the manager works on all domains, and open an issue to add more fine-grained validation later.

**Comment by jefflau** [comment]
The reason why 'resolver' is valid is because we would also need to check root domains. So to check the 'eth' route, you would search 'eth'.

Again this is only for directly going to /name/[name] without going through search, which still has some sanitisation

**Comment by makoto** [comment]
> The reason why 'resolver' is valid is because we would also need to check root domains. So to check the 'eth' route, you would search 'eth'.
> 

Ah, good point. I updated the issue to say `a` is valid.

> Again this is only for directly going to /name/[name] without going through search, which still has some sanitisation

The seven char length check actually from search actually invalidates many of the validation rules I listed. Now that's gone people will see the error message if they search `abcdefg..eth` from the search page.

screenshot 2019-02-20 at 09 30 08

Should this be addressed on this PR, or the new github issue?

**Comment by Arachnid** [comment]
If 'name to short' is ever being returned now, that seems like an issue with  this PR.

**Comment by makoto** [comment]
> If 'name to short' is ever being returned now, that seems like an issue with this PR.

The previous code shows the error (the page right), but this PR simply blows up (the page left).
I've seen this type of error when ens resolver fails to return correct address (eg: connecting to non supported network). I wonder if it occurs because it tries to resolve empty string domain on `a..eth`.

**Comment by jefflau** [comment]
So I've identified the bug, which is the namehash function is blowing up, because it's trying to get the `web3.utils.sha3` of an empty string and that returns null by web3, and then you can't slice null (to get rid of the `0x`, so it blows up. I'm thinking whether I should at least sanitise the name for domains like a....eth and show an error if that occurs or just edit the namehash function to start hashing '0', if it sees a null.

**Comment by jefflau** [comment]
Closing this and opening a new branch with leaving only domain sanitisation in

**Pull request closed without merging**
