### PR TITLE
bigcook12345.eth/Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by bigcook12345**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

## List of features added/changed

-
-
-

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My code implements all the required features.

### CODE REVIEW

**Review by bigcook12345 — COMMENTED** [review]
took me quite some time. got a bit frustrated for sure. I'm hoping this got it together this time around?

**Comment by makoto** [comment]
Hi, Thank you for your PR. I am not aware of what gitpod is. Are there any other projects where this sort of PR is merged? I would like to play around to evaluate whether I merge this PR or not.

**Comment by bigcook12345** [comment]
So.......

Real quick, I'm really trying to understand..?

The purpose, for example...

I'm genuinly not any sort of "Hacker" 🤔?

This is the 1st time i actually play around with the "Coding" network.

Fully on board with trying to be able to move forward with understanding,
and navigating, the in's and out's. Of how to try and properly, well. Which
I'm fully still not there obviously. Of how this all works?

Can you kindly explain to me of how and or what is going on with the
responses I've been receiving? I'd surely appreciate it 🤷‍♂️.

I've been learning it all with youtube video's of how to properly work the
network, and have done it all from an old cell phone i normally play
"Galaga" on.

More than anything, i wasnt even getting some of the emails..? But what
I've been contributing to, the "respitories", my branches stopped working,
passing, as well as getting deleted..? Plus the "Merging Block" started
again. Especially after it was passing. But it wasnt passing before..? Was
there a step that i missed..? Plus, the only ones that i inserted my
information, was after the "Merging" was approved? Plus the ones that i
helped complete..?
Just gone..?

I thought i was doing pretty good, at actually not making as much mistakes
as i was a month ago..?

**Comment by makoto** [comment]
Sorry but I don't understand your response at all, so closing

**Pull request closed without merging**
