### PR TITLE
Display grace period

### PR DESCRIPTION
**Pull request by makoto**
This will address https://github.com/ensdomains/ens-app/issues/363
Depending on https://github.com/ensdomains/ui/pull/12

The fix will display

- "Not owned" (instead of "Not owned yet")
- Displays the end of grace period
- Displays correct expiration period
- Allows anyone to renew

Screenshot 2019-07-09 at 14 39 56

### CODE REVIEW

**Comment by makoto** [comment]
The branch is deployed at https://imaginary-summer.surge.sh/name/omnivorous.eth

**Comment by jefflau** [comment]
Parked until design from @rliebert90 comes through

**Comment by rliebert90** [comment]
@makoto and @jefflau this is my solution for the grace period treatment (let me know if you have any feedback): 
Screen Shot 2019-07-15 at 7 21 54 PM

Here's the sketch file of this treatment: https://www.dropbox.com/s/xhb10lva2i9up18/ENS_Expiration-grace-period_07.15.19.sketch?dl=0

**Comment by jefflau** [comment]
> @makoto and @jefflau this is my solution for the grace period treatment (let me know if you have any feedback):
> Screen Shot 2019-07-15 at 7 21 54 PM
> 
> Here's the sketch file of this treatment: https://www.dropbox.com/s/xhb10lva2i9up18/ENS_Expiration-grace-period_07.15.19.sketch?dl=0

@rliebert90  Feels strange that it incuts everything inside the highlight. I have grown used to that style as stage in the UI where the incut style is where I have clicked to update something and it is showing me new information to input (i.e. setting the owner I have to add the owner), but I assume this appears as soon as they enter the UI. Is there a way we can solve this graphically without the incut?

**Comment by rliebert90** [comment]
@jefflau it can be a lot more subtle if that's what you're looking for. How about this? 

Screen Shot 2019-07-16 at 9 25 56 AM

**Comment by makoto** [comment]
@jefflau @rliebert90 does this look okay?
Screenshot 2019-08-13 at 11 31 17

**Comment by rliebert90** [comment]
@makoto this looks good! One tiny thing, looks like a space is missing in the beginning of the second sentence - between the . and 'Grace'.

**Comment by jefflau** [comment]
@makoto Font for expiring soon and 'grace period ends' seems to be in monospace, the design seems to be in non-monospace which looks better. It also seems a little too large. Becca's design has a slightly smaller font

**Comment by makoto** [comment]
Better?
Screenshot 2019-08-14 at 11 12 11

**Comment by jefflau** [comment]
Looks perfect

**Pull request merged**
